openapi: 3.0.0
info:
  title: WASAText API
  description: API for the WASAText messaging platform.
  version: 1.0.0

tags:
  - name: User
    description: Operations related to user management
  - name: Conversations
    description: Operations related to conversations
  - name: Messages
    description: Operations related to messages
  - name: Groups
    description: Operations related to groups

security:
  - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

  schemas:
    User:
      type: object
      description: User details.
      properties:
        id:
          type: string
          description: Unique user identifier.
          pattern: "^[a-zA-Z0-9_-]{12}$"
          minLength: 12
          example: "abcdef012345"
        name:
          type: string
          description: Username.
          pattern: "^[a-zA-Z0-9_-]{3,16}$"
          minLength: 3
          maxLength: 16
          example: "Maria"
    Conversation:
      type: object
      description: Details of a conversation.
      properties:
        id:
          type: string
          description: Unique conversation identifier.
          pattern: "^[a-zA-Z0-9_-]+$"
          minLength: 1
          example: "conversation123"
        name:
          type: string
          description: Name of the conversation.
          pattern: "^[a-zA-Z0-9_-]{1,255}$"
          minLength: 1
          maxLength: 255
          example: "Group Chat"
        lastMessage:
          type: string
          description: Last message preview.
          pattern: "^.{0,100}$"
          minLength: 0
          maxLength: 100
          example: "Hey, how are you?"
        timestamp:
          type: string
          format: date-time
          description: Timestamp of the last message.
          example: "2023-11-19T14:48:00.000Z"
    Message:
      type: object
      description: Details of a message.
      properties:
        id:
          type: string
          description: Unique message identifier.
          pattern: "^[a-zA-Z0-9_-]+$"
          minLength: 1
          example: "message123"
        sender:
          type: string
          description: Sender's username.
          pattern: "^[a-zA-Z0-9_-]{1,16}$"
          minLength: 1
          maxLength: 16
          example: "John"
        content:
          type: string
          description: Message content.
          pattern: "^.{0,500}$"
          minLength: 1
          maxLength: 500
          example: "Hello there!"
        timestamp:
          type: string
          format: date-time
          description: Timestamp of the message.
          example: "2023-11-19T14:48:00.000Z"
   
paths:
  /session:
    post:
      tags:
        - User
      summary: Logs in the user
      operationId: doLogin
      security: [] # no authentication required for login
      description: >
        If the user does not exist, it will be created. If the user exists, the user identifier is returned.
      requestBody:
        description: User Login details
        required: true
        content:
          application/json:
            schema:
               $ref: "#/components/schemas/User"
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema:
                description: The user identifier after a successful log-in.
                type: object
                properties:
                  description: A unique identifier for the user
                  identifier:
                    type: string
                    pattern: "^[a-zA-Z0-9_-]{12}$"
                    minLength: 12
                    example: "abcdef012345"

  /users/me/name:
    put:
      tags:
        - User
      summary: Update user name
      description: Update the username of the currently logged-in user
      operationId: setMyUserName
      requestBody:
        description: New username
        required: true
        content:
          application/json:
            schema:
              description: Creating anew username
              type: object
              properties:
                name:
                  type: string
                  description: New username.
                  pattern: "^[a-zA-Z0-9_-]{3,16}$"
                  minLength: 3
                  maxLength: 16
                  example: "new_username"
      responses:
        '200':
          description: Name updated successfully
          content:
            application/json:
              schema:
                description: The success status of the name update
                type: object
                properties:
                  description: Name update successful
                  success:
                    type: boolean
                    example: true
        '400':
          description: Username already exists
          content:
            application/json:
              schema:
                description: The error message explaining the username already exists
                type: object
                properties:
                  description: Username already exists
                  error:
                    type: string
                    description: Error message explaining the issue.
                    example: "The username is already taken."

  /users/me/photo:
    put:
      tags:
        - User
      summary: Update profile photo
      description: Allows the user to upload or change their profile photo
      operationId: setMyPhoto
      requestBody:
        description: Profile photo upload
        required: true
        content:
          multipart/form-data:
            schema:
              description: Uploading a profile photo
              type: object
              properties:
                description: The profile photo to be uploaded
                photo:
                  type: string
                  format: binary
                  minLength: 1
                  maxLength: 10000000
                  pattern: ".+"
      responses:
        '200':
          description: Photo updated successfully
          content:
            application/json:
              schema:
                description: Photo update successful
                type: object
                properties:
                  description: The success status of the photo update
                  success:
                    type: boolean
                    example: true

  /conversations:
    get:
      tags:
        - Conversations
      summary: Retrieve all conversations
      description: Fetch a list of all user conversations
      operationId: getMyConversations
      responses:
        '200':
          description: List of conversations
          content:
            application/json:
              schema:
                description: The list of conversations
                type: array
                items:
                  $ref: "#/components/schemas/Conversation"

  /conversations/{id}:
    get:
      tags:
        - Conversations
      summary: Retrieve messages in a conversation
      description: Fetch details of a specific conversation by its ID
      operationId: getConversation
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Conversation ID
      responses:
        '200':
          description: List of messages
          content:
            application/json:
              schema:
                description: The list of messages in the conversation
                type: array
                items:
                  $ref: "#/components/schemas/Message"

  /messages:
    post:
      tags:
        - Messages
      summary: Send a new message
      description: Send a message to a conversation
      operationId: sendMessage
      requestBody:
        description: Message details
        required: true
        content:
          application/json:
            schema:
              description: Sending a new message
              type: object
              properties:
                description: The conversation ID where the message will be sent and content of the message
                conversationId:
                  type: string
                  description: Conversation ID where the message will be sent.
                  example: "conversation123"
                  pattern: "^[a-zA-Z0-9_-]+$"
                  minLength: 1
                  maxLength: 50
                content:
                  type: string
                  description: Content of the message.
                  minLength: 1
                  maxLength: 500
                  pattern: ".+"
                  example: "Hello!"
      responses:
        '201':
          description: Message sent successfully
          content:
            application/json:
              schema:
                description: Message sent successfully
                type: object
                properties:
                  description: The success status of the message sending
                  success:
                    type: boolean
                    example: true

  /messages/{id}/forward:
    post:
      tags:
        - Messages
      summary: Forward a message
      description: Allows a user to forward a message to another conversation
      operationId: forwardMessage
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            pattern: "^[a-zA-Z0-9_-]+$"
            minLength: 1
            maxLength: 50
          description: Message ID to forward
      requestBody:
        description: Forwarding details
        required: true
        content:
          application/json:
            schema:
              description: Forwarding a message
              type: object
              properties:
                toConversationId:
                  type: string
                  description: The ID of the conversation to forward the message to
                  pattern: "^[a-zA-Z0-9_-]+$"
                  minLength: 1
                  maxLength: 50 
                  example: "conversation456"
      responses:
        '201':
          description: Message forwarded successfully
          content:
            application/json:
              schema:
                description: The success status of the message forwarding
                type: object
                properties:
                  description: Message forwarded successfully
                  success:
                    type: boolean
                    example: true

  /messages/{id}/comment:
    post:
      tags:
        - Messages
      summary: Add a like to a message
      description: Allows an user to like a message
      operationId: commentMessage
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            pattern: "^[a-zA-Z0-9_-]+$"
            minLength: 1
            maxLength: 50
          description: Message ID to like to
      requestBody:
        description: Reaction details
        required: true
        content:
          application/json:
            schema:
              description: Adding a like to a message
              type: object
              properties:
                type:
                  type: string
                  description: Type of like (e.g., "like")
                  pattern: "^[a-zA-Z]+$"
                  minLength: 1
                  maxLength: 20
                  example: "like"
      responses:
        '201':
          description: Reaction added successfully
          content:
            application/json:
              schema:
                description: The success status of the like adding
                type: object
                properties:
                  description: Like added successfully
                  success:
                    type: boolean
                    example: true
    delete:
      tags:
        - Messages
      summary: Remove a like from a message
      description: Allows an user to remove a like from a message
      operationId: uncommentMessage
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            pattern: "^[a-zA-Z0-9_-]+$"
            minLength: 1
            maxLength: 50
          description: Message ID to remove like from
      responses:
        '200':
          description: Like removed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  description: Like removed successfully
                  success:
                    type: boolean
                    example: true
                    
  /messages/{id}/delete:
    delete:
      tags:
        - Messages
      summary: Delete a message
      description: Allows a user to delete a message they sent.
      operationId: deleteMessage
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            minLength: 1
            maxLength: 50
            pattern: "^[a-zA-Z0-9_-]+$"
          description: Message ID to delete.
      responses:
        '200':
          description: Message deleted successfully
          content:
            application/json:
              schema:
                description: The success status of the message deletion
                type: object
                properties:
                  description: Message deleted successfully
                  success:
                    type: boolean
                    example: true       
                    
  /groups/{id}/add:
    post:
      tags:
        - Groups
      summary: Add a user to a group
      description: Allows an admin to add a user to a group.
      operationId: addToGroup
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            pattern: "^[a-zA-Z0-9_-]+$"
            minLength: 1
            maxLength: 50
          description: Group ID.
      requestBody:
        description: User to be added to the group.
        required: true
        content:
          application/json:
            schema:
              description: Adding a user to a group
              type: object
              properties:
                userId:
                  type: string
                  description: User ID of the person to add to the group.
                  minLength: 1
                  maxLength: 50
                  pattern: "^[a-zA-Z0-9_-]+$"
                  example: "user123"
      responses:
        '200':
          description: User added successfully
          content:
            application/json:
              schema:
                description: The success status of the user adding
                type: object
                properties:
                  description: User added successfully
                  success:
                    type: boolean
                    example: true
  
  /groups/{id}/name:
    put:
      tags:
        - Groups
      summary: Update group name
      description: Allows an admin to update the name of a group.
      operationId: setGroupName
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            pattern: "^[a-zA-Z0-9_-]+$"
            minLength: 1
            maxLength: 50
          description: Group ID.
      requestBody:
        description: New name for the group.
        required: true
        content:
          application/json:
            schema:
              description: Updating the name of a group
              type: object
              properties:
                name:
                  type: string
                  description: New name for the group.
                  minLength: 3
                  maxLength: 100
                  pattern: "^[a-zA-Z0-9_-]+$"
                  example: "New Group Name"
      responses:
        '200':
          description: Group name updated successfully
          content:
            application/json:
              schema:
                description: The success status of the group name update
                type: object
                properties:
                  description: Group name updated successfully
                  success:
                    type: boolean
                    example: true

  /groups/{id}/leave:
    post:
      tags:
        - Groups
      summary: Leave a group
      description: Allows an user to leave to a group
      operationId: leaveGroup
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            pattern: "^[a-zA-Z0-9_-]+$"
            minLength: 1
            maxLength: 50
          description: Group ID to leave
      responses:
        '200':
          description: Left group successfully
          content:
            application/json:
              schema:
                description: The success status of the group leaving
                type: object
                properties:
                  description: Left group successfully
                  success:
                    type: boolean
                    example: true

  /groups/{id}/photo:
    put:
      tags:
        - Groups
      summary: Update group photo
      description: Allows an admin to upload or update the group's photo
      operationId: setGroupPhoto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            pattern: "^[a-zA-Z0-9_-]+$"
            minLength: 1
            maxLength: 50
          description: Group ID
      requestBody:
        description: Group photo upload
        required: true
        content:
          multipart/form-data:
            schema:
              description: Uploading a group photo
              type: object
              properties:
                description: The group photo to be uploaded
                photo:
                  type: string
                  format: binary
                  minLength: 1
                  maxLength: 10000000
                  pattern: ".+"
      responses:
        '200':
          description: Group photo updated successfully
          content:
            application/json:
              schema:
                description: The success status of the group photo update
                type: object
                properties:
                  description: Group photo updated successfully
                  success:
                    type: boolean
                    example: true
